### ISSUE TITLE
关于Streamlit在线服务器体验网址打不开的问题

### ISSUE THREAD

**Issue by canglang007** [Kedreamix/YoloGesture#2]
点击体验网址后会有报错ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).

**Comment by Kedreamix** [comment]
我觉得可能是streamlit的问题，针对这个问题确实有人出现过，我打算近期如果有时间的话，给一个gradio的界面出来吧
